"""Clinical concept-to-category mapping for targeted RAG retrieval."""

CONCEPT_CATEGORY_MAP = {
    "gi bleed": ["labs", "medications", "vitals", "notes"],
    "gastrointestinal": ["labs", "medications", "notes"],
    "hemorrhage": ["labs", "medications", "vitals"],
    "bleeding": ["labs", "medications", "vitals", "notes"],
    "hemoglobin": ["labs"],
    "anemia": ["labs"],
    "pe": ["labs", "vitals", "medications", "notes", "history"],
    "pulmonary embolism": ["labs", "vitals", "medications", "notes", "history"],
    "dvt": ["labs", "medications", "notes", "history", "imaging"],
    "vte": ["labs", "medications", "notes", "history"],
    "hit": ["labs", "medications", "allergies", "notes", "problems"],
    "heparin": ["medications", "allergies", "notes", "problems"],
    "thrombocytopenia": ["labs", "medications", "allergies", "notes"],
    "platelets": ["labs", "medications", "allergies"],
    "hypotension": ["vitals", "labs", "medications"],
    "tachycardia": ["vitals", "labs"],
    "sepsis": ["vitals", "labs", "medications", "notes"],
    "anticoagulation": ["medications", "allergies", "labs", "notes"],
    "wells": ["vitals", "history", "notes", "labs"],
    "sofa": ["vitals", "labs"],
    "vital": ["vitals", "labs"],
    "blood pressure": ["vitals"],
    "heart rate": ["vitals"],
    "temperature": ["vitals"],
    "spo2": ["vitals"],
    "oxygen": ["vitals"],
    "lab": ["labs"],
    "score": ["labs", "vitals", "notes", "history", "medications"],
    "heart score": ["labs", "vitals", "notes", "history", "medications"],
    "grace": ["labs", "vitals", "notes", "history", "medications"],
    "trend": ["labs", "vitals"],
    "imaging": ["imaging"],
    "xray": ["imaging"],
    "ct": ["imaging"],
    "note": ["notes"],
    "history": ["history", "notes"],
    "medication": ["medications"],
    "allergy": ["allergies"],
    "diagnosis": ["problems", "notes"],
    "surgery": ["notes", "imaging"],
    "post.op": ["vitals", "labs", "medications", "notes"],
}

SAFETY_ALWAYS_RETRIEVE = ["allergies", "problems", "medications"]
